### ISSUE TITLE
Additional resource downloads

### ISSUE THREAD

**Issue by ConstructionCompleted** [NotThorny/Cultivation#15]
Is it normal to download approximately 500MB of new resources on the login interface?
What I did before this:
move the Grasscutter into the virtual machine.
Change the accessAddress to the virtual machine IP.
Download the 4.7 international server through the official link.
Manually set 47version.dll and renamed it.
Download mihoyonet.dll (4.2.0) for LunaC_4.6.0 and replace it. Otherwise, it will always prompt 'Network timeout, please try again later'.

Addendum after writing: After the above operations, the login can be successful, but the screen remains blank.

**Comment by NotThorny** [comment]
This kind of download would be a passthrough from the server software you are using. So this would be something determined by LunaGC rather than Cultivation.

Cultivation already supports automatically patching version dll and hoyonet dll, so in general you should not be replacing them manually.

It sounds like you're mixing two different versions though. If you're using LunaGC for 4.6, you need a 4.6 client and patch for it, not 4.7. I would imagine the "screen remains blank" is due to the error (likely 4214) being hooked by the patch. You will see the error in the patch cmd instead of on the game screen.

I would say to let Cultivation handle patching automatically rather than manually switching dlls around. Any issues after that are generally going to be due to the server software you are using.

**Comment by ConstructionCompleted** [comment]
Thanks, I have already resolved this issue a few days ago, indeed through automatic patching.
